export const cakeTypeList = ["cienkie", "grube", "serowymi brzegam"];
export const typeList = ["własna", "składana"];
export const defPizza = {
  type: "własna",
  cake: "cienkie",
  ingredients: [],
};
export const ingredientsList = [
  "Mozzarella",
  "Pieczarki",
  "Szynka",
  "Salami",
  "Rukola",
  "Pomidor",
  "Papryka",
  "Kukurydza",
  "Papryczka Peperoni",
  "Ananas",
  "Suszone pomidory",
  "Oliwki",
  "Bekon",
  "Cebula",
  "Jajko",
  "Tabasko",
  "Czosnek",
  "Świeży brokuł",
  "Jalapeno",
  "Parmezan",
  "Gorgonzola",
  "Feta",
  "Bazylia",
  "Orygano",
  "Kabanos",
  "Kurczak",
  "Ogórek",
  "Cebula czerwona",
  "Tuńczyk",
  "Boczek",
  "Kiełbasa",
  "Chorizo",
  "Czerwona fasola",
  "Szczypiorek",
  "Szynka parmeńska",
];
